Fix overloads, destructors, deprecation, don't output entire config file to screen
ori-drs/lidar_undistortion pull request #16
Opened 2021-02-23 13:19 UTC by wxmerkt

2021-02-23 13:24 UTC, mauricefallon commented
have you tested this?

2021-02-23 14:14 UTC, wxmerkt commented
Yes I am running it with the Spot log on Noetic

2021-02-23 14:18 UTC, mauricefallon commented
Ok, awesome. That's pretty dedicated of you!

The improvement with undistortion on the clouds fed with Spot's odometry is clear cut.

2021-02-23 14:23 UTC, mcamurri commented
Thank you @wxmerkt . I was aware of the annoying PCL warning but wasn't sure how to fix it properly.

2021-02-23 14:59 UTC, mcamurri requested changes
All good

2021-02-23 14:59 UTC, mcamurri commented on lidar_undistortion_ros/include/lidar_undistortion_ros/ouster_undistorter_ros.hpp
> + virtual ~OusterUndistorterROS() = default;
I believe you can set it as override, the super destructor should be virtual:
`~OusterUndistorterRos() override = default;`

2021-02-23 15:22 UTC, wxmerkt commented
It does make a large difference - I am using it to have "better" point clouds going into the GaitMesh reconstruction. And it improves the surface planes/normals we get.

2021-02-23 15:32 UTC, mauricefallon commented
I dont know if you are accumulating the point clouds yourself or using elevation mapping
EM is pretty good:
https://www.dropbox.com/s/k1nxx5xfjp1k2pa/spot_elevation_mapping3.mp4?dl=0
but you need to turn off visibility clear out in the elevation mapping setting.

2021-02-24 08:43 UTC, mcamurri commented
[jenkins test this]

2021-02-24 08:44 UTC, mcamurri approved these changes

2021-02-24 09:58 UTC, wxmerkt commented
We've been accumulating point clouds ourselves but I am moving to using EM (since otherwise the floor is too sparse), thanks for the pointer :-)

The CI failure is due to a CI configuration issue - it is not extending any upstream workspace (cc @benoit-robotics):

```
--------------------------------------------------------------------------------
Profile:                     default
**Extending:                   None**
Workspace:                   /var/lib/jenkins/workspace/drs_pr_ori_drs_lidar_undistortion/catkin_ws
--------------------------------------------------------------------------------
``` 

Extending says "None" when it should read `/opt/ros/DISTRO`

2021-02-24 13:20 UTC, benoit-robotics commented
the CI fails because the build server hasn't been entirely migrated  to Ubuntu 20, I hope to finish that soon

2021-03-01 10:01 UTC, merged