change check on start timestamp
ori-drs/lidar_undistortion pull request #19
Opened 2021-05-06 11:01 UTC by dwisth

@mcamurri 

This changes the check on the timestamps in the undistorter.

This fixes an edge case where we try to undistort the point cloud to a time between the point cloud header time, and the time of the first point in the cloud (see diagram below).

![image](https://user-images.githubusercontent.com/6793487/117287769-9bde5780-ae62-11eb-80e4-205ca2a99ba1.png)

2021-05-06 11:19 UTC, wxmerkt commented on lidar_undistortion/include/lidar_undistortion/lidar_undistorter.hpp
> +  uint64_t t_end =   start_timestamp + static_cast<uint64_t>(*minmax_time.second);
This appears to be a fix for a bug that could be caught when turning on all warnings more aggressively by default and fixing the arising warnings: `-Wall -Wpedantic -Wextra`

2021-05-06 12:22 UTC, dwisth commented on lidar_undistortion/include/lidar_undistortion/lidar_undistorter.hpp
> +  uint64_t t_end =   start_timestamp + static_cast<uint64_t>(*minmax_time.second);
True - this should be picked up by those warnings. The types are `uint64_t` and `int32_t` and the first variable `uint64_t` can be a very large number (the ros timestamp in nanoseconds).

This wasn't the main bug that I was trying to fix but should be resolved.

2021-05-06 12:34 UTC, mcamurri commented
In no case `start_timestamp` and `t_start` should be different. If this happens, it means the point cloud was badly timestamp in the first place, so the problem should be fixed at the acquisition of the point cloud and not here. I agree there should be here an extra check that `start_timestamp` and `t_start` should be identical and it should fire an error if this is not a case.

Regarding the static casting, it should be something like this:
```cpp
uint64_t t_start = static_cast<uint64_t>(static_cast<int64_t>(start_timestamp) + static_cast<int64_t>(*minmax_time.first))
```

2021-06-08 17:37 UTC, mcamurri requested changes
I would add the static casting as shown in my previous comment

2021-07-06 14:18 UTC, merged